// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6VvC5zVPXQZFM2KILnTcA2xOLIzSMvw',
    appId: '1:36635616416:web:5c26cbd79c6f5bd42895c5',
    messagingSenderId: '36635616416',
    projectId: 'freelancer-ac58e',
    authDomain: 'freelancer-ac58e.firebaseapp.com',
    storageBucket: 'freelancer-ac58e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJejEzcaojvMdFsavIWES1W1fXkA0m868',
    appId: '1:36635616416:android:87325ad43482e4a12895c5',
    messagingSenderId: '36635616416',
    projectId: 'freelancer-ac58e',
    storageBucket: 'freelancer-ac58e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmdEvdNBNKEZr4DML3UBGSamuxlXuvIPU',
    appId: '1:36635616416:ios:21f496aed2cc31a52895c5',
    messagingSenderId: '36635616416',
    projectId: 'freelancer-ac58e',
    storageBucket: 'freelancer-ac58e.appspot.com',
    iosBundleId: 'com.example.freelance2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmdEvdNBNKEZr4DML3UBGSamuxlXuvIPU',
    appId: '1:36635616416:ios:21f496aed2cc31a52895c5',
    messagingSenderId: '36635616416',
    projectId: 'freelancer-ac58e',
    storageBucket: 'freelancer-ac58e.appspot.com',
    iosBundleId: 'com.example.freelance2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm6VvC5zVPXQZFM2KILnTcA2xOLIzSMvw',
    appId: '1:36635616416:web:c62c866600181f352895c5',
    messagingSenderId: '36635616416',
    projectId: 'freelancer-ac58e',
    authDomain: 'freelancer-ac58e.firebaseapp.com',
    storageBucket: 'freelancer-ac58e.appspot.com',
  );
}
